### ISSUE TITLE
Struct field all null even if it does not exist

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/deltalake2db#1]
"multilangValue": {
            "de": "verchromt - schwarz poliert",
            "fr": "chromé - noir poli",
            "it": "cromato - nero brunito",
            "$inv": "187"
          }
        },
        {
          "groupId": "generic_sanitary_product",
          "code": "Hersteller",
          "value": "TECE",
          "valueType": "string",
          "isSearchable": "True",
          "multilangValue": {
            "de": null,
            "fr": null,
            "it": null,
            "$inv": null
          }

**Comment by aersam** [comment]
It's not fixed, polars and duckdb do have different trouble here:

- Polars just returns always a struct and not null, even when using read_parquet directly. No way to distinguish from null
- Duckdb correctly gives null, but: `duckdb.execute("""Select { 'lat': 1 } as tester union all select Null""").fetchall()` gives you two structs again
